### ISSUE TITLE
How can I get the code of schism_0.9.2

### ISSUE THREAD

**Issue by lj-cug** [CADWRDeltaModeling/cyclecloud-schism#1]
As I know, the cloud computation of SCHISM model is different with the host-couputer version, Where can I get the rpm of Intel Compiler and runtime as well as the SCHISM_v0.9.2 used in the cyclecloud. Sorry for the stupid question, I am a new begineer in the cloud computation. -Li Jian

**Comment by kjnam** [comment]
Please take a look at the release tab: https://github.com/CADWRDeltaModeling/cyclecloud-schism/releases
