### ISSUE TITLE
Some question about cyclecoud

### ISSUE THREAD

**Issue by lj-cug** [CADWRDeltaModeling/cyclecloud-schism#2]
Dear Sir:
    Some questions about the cyclecould I should consult with you. 
(1) If I want to run the SCHISM on cyclecloud, do I have to use SCHISM_v0.9.2? And I also have to upload the Intel 2016 RPM files and the SCHISM code in blobs into the cyclecloud? As I comprehend, the Intel compiler, runtime and the openmp/ MPICH library was installed on the nodes in the cyclecloud, am I right?
(2) Can I use Windows OS in cyclecloud?
(3) Can I compile the SCHISM code into executable, and upload the executable into cyclecloud?
Much Thanks!
-- Li Jian from China

**Comment by kjnam** [comment]
1. v0.9.2 is the latest working one, and it can be found in the release tab. Intel runtimes are included. The H15r works well with Intel 2016 MPI, and this release uses it.
2. I doubt it.
3. Yes, of course. Once you create and start a cluster, it behaves like a plain cluster. You can do pretty much anything that you do like compiling.
